# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: cobot_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - agv_casterwheel_11_joint
    - agv_casterwheel_12_joint
    - agv_casterwheel_21_joint
    - agv_casterwheel_22_joint
    - agv_casterwheel_31_joint
    - agv_casterwheel_32_joint
    - agv_casterwheel_41_joint
    - agv_casterwheel_42
    - agv_leftwheel_joint
    - agv_rightwheel_joint
    - agv_cobot_1_joint
    - agv_cobot_2_joint
    - agv_cobot_3_joint
    - agv_cobot_4_joint
    - agv_cobot_5_joint
    - agv_cobot_6_joint
    - agv_cobot_7_base
    - agv_leftgrip_joint
    - agv_rightgrip_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: cobot_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - agv_cobot_1_joint
      - agv_cobot_2_joint
      - agv_cobot_3_joint
      - agv_cobot_4_joint
      - agv_cobot_5_joint
      - agv_cobot_6_joint
      - agv_cobot_7_base
  - name: cobot_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - agv_leftgrip_joint
      - agv_rightgrip_joint
cobot_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - agv_cobot_1_joint
    - agv_cobot_2_joint
    - agv_cobot_3_joint
    - agv_cobot_4_joint
    - agv_cobot_5_joint
    - agv_cobot_6_joint
    - agv_cobot_7_base
  gains:
    agv_cobot_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    agv_cobot_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    agv_cobot_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    agv_cobot_4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    agv_cobot_5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    agv_cobot_6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    agv_cobot_7_base:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
cobot_hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - agv_leftgrip_joint
    - agv_rightgrip_joint
  gains:
    agv_leftgrip_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    agv_rightgrip_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
