rivet:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: scara_rivet_base_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}


