cobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: agv_cobot_1_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: agv_cobot_2_joint
    pid: {p: 2000.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: agv_cobot_3_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: agv_cobot_4_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: agv_cobot_5_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: agv_cobot_6_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: agv_cobot_7_joint
    pid: {p: 1000.0, i: 0.01, d: 1.0}
  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: agv_leftgrip_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: agv_rightgrip_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}



