# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_bgrip
  joint_model_group_pose: bgrip_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - scara_1_joint
    - scara_2_joint
    - scara_3_joint
    - scara_4_joint
    - scara_dualgrip_base_joint
    - scara_dualgrip_big_leftgrip_joint
    - scara_dualgrip_big_rightgrip_joint
    - scara_dualgrip_revolute_joint
    - scara_dualgrip_small_leftgrip_joint
    - scara_dualgrip_small_rightgrip_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_bgrip_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - scara_1_joint
      - scara_2_joint
      - scara_3_joint
      - scara_4_joint
      - scara_dualgrip_base_joint
#  - name: arm_sgrip_controller
#    action_ns: follow_joint_trajectory
#    default: True
#    type: FollowJointTrajectory
#    joints:
#      - scara_1_joint
#      - scara_2_joint
#      - scara_3_joint
#      - scara_4_joint
#      - scara_dualgrip_base_joint
  - name: big_grip_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - scara_dualgrip_big_leftgrip_joint
      - scara_dualgrip_big_rightgrip_joint
  - name: small_grip_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - scara_dualgrip_revolute_joint
      - scara_dualgrip_small_leftgrip_joint
      - scara_dualgrip_small_rightgrip_joint
arm_bgrip_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - scara_1_joint
    - scara_2_joint
    - scara_3_joint
    - scara_4_joint
    - scara_dualgrip_base_joint
  gains:
    scara_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    scara_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    scara_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    scara_4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    scara_dualgrip_base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
#arm_sgrip_controller:
#  type: position_controllers/JointTrajectoryController
#  joints:
#    - scara_1_joint
#    - scara_2_joint
#    - scara_3_joint
#    - scara_4_joint
#    - scara_dualgrip_base_joint
#  gains:
#    scara_1_joint:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    scara_2_joint:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    scara_3_joint:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    scara_4_joint:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    scara_dualgrip_base_joint:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
small_grip_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - scara_dualgrip_revolute_joint
    - scara_dualgrip_small_leftgrip_joint
    - scara_dualgrip_small_rightgrip_joint
  gains:
    scara_dualgrip_revolute_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    scara_dualgrip_small_leftgrip_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    scara_dualgrip_small_rightgrip_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
big_grip_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - scara_dualgrip_big_leftgrip_joint
    - scara_dualgrip_big_rightgrip_joint
  gains:
    scara_dualgrip_big_leftgrip_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    scara_dualgrip_big_rightgrip_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
